# Generated by Django 5.2.8 on 2025-11-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pedido_itempedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='prato',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
